/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kemahasiswaan_10119010_10119028;

/**
 *
 * @author RizalSihombing
 */
public class frame_utama extends javax.swing.JFrame {

    /**
     * Creates new form frame_utama
     */
    public frame_utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_DataMahasiswa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_DataMataKuliah = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_DataNilai = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_SimulasiNilaiAkhir = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_SimulasiKasus = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(74, 31, 61));
        jToolBar1.setRollover(true);

        btn_DataMahasiswa.setBackground(new java.awt.Color(74, 31, 61));
        btn_DataMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        btn_DataMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mahasiswa.png"))); // NOI18N
        btn_DataMahasiswa.setText("Data Mahasiswa");
        btn_DataMahasiswa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 79, 84)));
        btn_DataMahasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DataMahasiswa.setFocusable(false);
        btn_DataMahasiswa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_DataMahasiswa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_DataMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DataMahasiswaMouseClicked(evt);
            }
        });
        jToolBar1.add(btn_DataMahasiswa);
        jToolBar1.add(jSeparator1);

        btn_DataMataKuliah.setBackground(new java.awt.Color(74, 31, 61));
        btn_DataMataKuliah.setForeground(new java.awt.Color(255, 255, 255));
        btn_DataMataKuliah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mata_kuliah.png"))); // NOI18N
        btn_DataMataKuliah.setText("Data Mata Kuliah");
        btn_DataMataKuliah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 79, 84)));
        btn_DataMataKuliah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DataMataKuliah.setFocusable(false);
        btn_DataMataKuliah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_DataMataKuliah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_DataMataKuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DataMataKuliahMouseClicked(evt);
            }
        });
        jToolBar1.add(btn_DataMataKuliah);
        jToolBar1.add(jSeparator2);

        btn_DataNilai.setBackground(new java.awt.Color(74, 31, 61));
        btn_DataNilai.setForeground(new java.awt.Color(255, 255, 255));
        btn_DataNilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/nilai.png"))); // NOI18N
        btn_DataNilai.setText("Data Nilai");
        btn_DataNilai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 79, 84)));
        btn_DataNilai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DataNilai.setFocusable(false);
        btn_DataNilai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_DataNilai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_DataNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DataNilaiMouseClicked(evt);
            }
        });
        jToolBar1.add(btn_DataNilai);
        jToolBar1.add(jSeparator3);

        btn_SimulasiNilaiAkhir.setBackground(new java.awt.Color(74, 31, 61));
        btn_SimulasiNilaiAkhir.setForeground(new java.awt.Color(255, 255, 255));
        btn_SimulasiNilaiAkhir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/nilai akhir.png"))); // NOI18N
        btn_SimulasiNilaiAkhir.setText("Simulasi Nilai Akhir");
        btn_SimulasiNilaiAkhir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 79, 84)));
        btn_SimulasiNilaiAkhir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_SimulasiNilaiAkhir.setFocusable(false);
        btn_SimulasiNilaiAkhir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_SimulasiNilaiAkhir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_SimulasiNilaiAkhir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SimulasiNilaiAkhirMouseClicked(evt);
            }
        });
        jToolBar1.add(btn_SimulasiNilaiAkhir);
        jToolBar1.add(jSeparator4);

        btn_SimulasiKasus.setBackground(new java.awt.Color(74, 31, 61));
        btn_SimulasiKasus.setForeground(new java.awt.Color(255, 255, 255));
        btn_SimulasiKasus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kasus.png"))); // NOI18N
        btn_SimulasiKasus.setText("Simulasi Kasus");
        btn_SimulasiKasus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 79, 84)));
        btn_SimulasiKasus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_SimulasiKasus.setFocusable(false);
        btn_SimulasiKasus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_SimulasiKasus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_SimulasiKasus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SimulasiKasusMouseClicked(evt);
            }
        });
        btn_SimulasiKasus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimulasiKasusActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_SimulasiKasus);
        jToolBar1.add(jSeparator5);

        jPanel2.setBackground(new java.awt.Color(186, 79, 84));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("10119010");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("10119028");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rizal Sihombing");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Maulana Imam Malik");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/foto rizal.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/foto imam.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)))))
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jMenu1.setText("Aplikasi Kemahasiswaan");

        jMenuItem1.setText("Tentang Pembuat");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DataMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataMahasiswaMouseClicked
        // TODO add your handling code here:
        // deklarasi frame_mahasiswa
        frame_mahasiswa frame_mahasiswa = new frame_mahasiswa();
        frame_mahasiswa.setVisible(true);
        
        // menghilangkan form utama
        this.setVisible(false);
    }//GEN-LAST:event_btn_DataMahasiswaMouseClicked

    private void btn_DataMataKuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataMataKuliahMouseClicked
        // TODO add your handling code here:
        // deklarasi frame_mataKuliah
        frame_mataKuliah frame_mataKuliah = new frame_mataKuliah();
        frame_mataKuliah.setVisible(true);
        
        // menghilangkan form utama
        this.setVisible(false);
    }//GEN-LAST:event_btn_DataMataKuliahMouseClicked

    private void btn_DataNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DataNilaiMouseClicked
        // TODO add your handling code here:
        // deklarasi frame_mataKuliah
        frame_nilaiMahasiswa frame_nilaiMahasiswa = new frame_nilaiMahasiswa();
        frame_nilaiMahasiswa.setVisible(true);
        
        // menghilangkan form utama
        this.setVisible(false);
    }//GEN-LAST:event_btn_DataNilaiMouseClicked

    private void btn_SimulasiNilaiAkhirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SimulasiNilaiAkhirMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        // deklarasi frame_mataKuliah
        frame_simulasiNilaiAkhir frame_simulasiNilaiAkhir = new frame_simulasiNilaiAkhir();
        frame_simulasiNilaiAkhir.setVisible(true);
        
        // menghilangkan form utama
        this.setVisible(false);
    }//GEN-LAST:event_btn_SimulasiNilaiAkhirMouseClicked

    private void btn_SimulasiKasusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SimulasiKasusMouseClicked
        // TODO add your handling code here:
        // Untuk Simulasi Kasus JGN DIHAPUS
    }//GEN-LAST:event_btn_SimulasiKasusMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        frame_login frame_login = new frame_login();
        frame_login.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btn_SimulasiKasusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimulasiKasusActionPerformed
        // TODO add your handling code here:
        frame_simulasiKasus kasus = new frame_simulasiKasus();
        kasus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_SimulasiKasusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DataMahasiswa;
    private javax.swing.JButton btn_DataMataKuliah;
    private javax.swing.JButton btn_DataNilai;
    private javax.swing.JButton btn_SimulasiKasus;
    private javax.swing.JButton btn_SimulasiNilaiAkhir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
